Updated Auto Item output; added documentation
zeldamods/radar pull request #12
Opened 2021-11-24 14:40 UTC by savage13

Updates the output from auto_object.ts
- Removed incorrect % sign
- Added documentation
- Removed likely irrelevant number from output (now as a `display:none` span)
  - The number is needed as the `title` is used as the object key 

Should the output `json` files be placed into a particular directory for easier updating?

objmap updates from this also coming.

2021-11-27 14:17 UTC, leoetlino requested changes

2021-11-27 14:17 UTC, leoetlino commented on auto_object.ts
> +      let key = `${atype}<br/>${parts.join('<br/>')}<br/>Field Map Area: ${num}<span style="display:none">${n}</span>`;
Hmm, it's a bit weird to have hidden HTML in the key... Actually I think there shouldn't be any HTML at all. Formatting should be done on the client side. Can we turn the entry format into the following?

```js
[
  {
    "type": atype,
    "field_map_area": num,
    "geom": geom,
    ... // any other useful properties
]
```

Basically just dump an array of objects with any necessary information and let the client do whatever it wishes with the data.

2021-11-28 13:04 UTC, savage13 commented
Removed the embedded HTML in the output JSON file

2021-11-28 13:54 UTC, leoetlino requested changes

2021-11-28 13:54 UTC, leoetlino commented on auto_object.ts
>        if (atype == "Safe") {
This can be removed now

2021-11-28 13:54 UTC, leoetlino commented on auto_object.ts
> +  console.log("       e.g. % ts-node auto_objects.ts -a ../botw/Actor")
```suggestion
  console.log("       e.g. % ts-node auto_object.ts -a ../botw/Actor")
```

2021-11-28 15:26 UTC, savage13 commented
I think I successfully made all of the changes.

2021-11-28 17:49 UTC, leoetlino approved these changes

2021-11-28 17:49 UTC, merged